### ISSUE TITLE
Decouple company-ycmd-enable-fuzzy-matching and cache-disabling

### ISSUE THREAD

**Issue by abingham** [abingham/emacs-ycmd#112]
In #111 we really highlighted the distinction between fuzzy-matching and caching. We need to de-conflate the two. That is, `company-ycmd-no-cache` should absolutely disable the cache, no matter whether fuzzy-matching is in use or not. Likewise, fuzzy-matching control should be independent of caching (though fuzzy-matching won't work keystroke-by-keystroke when caching is disabled.) We could even go so far as to remove fuzzy-matching control completely, effectively leaving it on all of the time.

**Comment by zhuzhongshu** [comment]
Hello, in this issue https://github.com/abingham/emacs-ycmd/issues/148, the problem springs from the conflict of `company-require-match` feature of `company-mode` and the fuzzy-matching feature of `company-ycmd`(which disable the comapny internal cache). How can I turn on the fuzzy-matching feature as well as enable the company internal cache, or it will be provided in future version?

**Comment by ptrv** [comment]
Unfortunately the variable name `company-ycmd-enable-fuzzy-matching` is a bit misleading. If the variable is non-nil company-ycmd will send completion requests to the ycmd server after every typed key and the server will return matches also with fuzzy matching. As far as I understood, to make this work properly, you have to disable company-mode's own cache feature. If the variable is nil we use the company any-mode cache and filter out non prefix candidates to not send completion requests to the server on every typed key in order to have a bit better performance. `company-ycmd-enable-fuzzy-matching` set to non-nil does not mean that we have fuzzy matching for the popup with results. I am not sure it makes sense to enable the company-mode cache and sending every key type a completion request to the server. This would make the cache obsolete.  @abingham what do you think?

**Comment by abingham** [comment]
@ptrv is correct. With fuzzy-matching enabled we have to assume that the company cache is invalid after every keystroke, so we simply disable it. 

It appears that this particular issue is unnecessary now. The `company-ycmd-no-cache` variable has been removed. I'm going to close this, but let me know if I'm mistaken and should keep it open.
