### ISSUE TITLE
c Completion in Scope.

### ISSUE THREAD

**Issue by Dickby** [abingham/emacs-ycmd#137]
After updating the package today, ycmd completes variables in c code everywhere in the file.
Before the update it was only possible to complete the variables in their scope, which i liked al lot.
Thanks.

**Comment by abingham** [comment]
Do you mean that you're getting completions that don't make sense for the scope? If so, it's probably due to the new controls we introduced for semantic vs. identifier-based completion. I think that if you set `ycmd-force-semantic-completion` to `t` then you'll get the behavior you want. You can test this quickly by running `M-x ycmd-toggle-force-semantic-completion` and seeing if it behaves the way you want.

**Comment by Dickby** [comment]
Whithout force-semantic-completion t, it isn't working at all, only the file-local things are completed.
I put ycmd-toggle-force-semantic-completion on a keybinding, because with it ycmd won't complete the c-header files. Now I'm toggling it nil for headers and t for code. 
But after updating I have the Behavior described in my last comment with force-semantic-completion t.

**Comment by abingham** [comment]
I'm not really sure what's going on, to be honest. I'm having trouble duplicating what you're seeing, but most of that trouble is because emacs seems to be hanging for certain kinds of completions. This could be a problem in any number of packages, so it could take me some time to debug.

In any case, the root of what you're seeing is possibly at `ycmd` itself. That is, with the exception of forcing semantic completion, `emacs-ycmd` simply reports the completions that `ycmd` returns. If `ycmd` has recently changed behaviors, then that may be causing what you're seeing.

@valloric Has `ycmd` changed behavior recently with regards to where/how it completes symbols in C code?

**Comment by Dickby** [comment]
I installed it again, and now it's working, it was my fault probably.
But it's still only possible to complete the c-header files if I toggle ycmd-force-semantic-completion nil.

**Comment by abingham** [comment]
I break my setup all the time by forgetting to update all the parts in synchrony. There are lots of moving parts!

As I understand things, ycmd is designed such that you should typically *not* try to force semantic completion. ycmd will try to "do the right thing" for a given situation, so leaving `ycmd-force-semantic-completion` as `nil` should normally be correct. You've probably already seen this, but the ycmd project has [some information on how it works](https://github.com/valloric/ycmd#how-ycmd-works).

Do you consider this issue closed, or are there still issues that I should try to look at?

**Comment by Dickby** [comment]
Thanks for your efforts, and for the Package.

**Comment by Valloric** [comment]
> @valloric Has ycmd changed behavior recently with regards to where/how it completes symbols in C code?

Nope.

> As I understand things, ycmd is designed such that you should typically not try to force semantic completion. 

Correct. Identifier completion is good enough for most use-cases. Semantic completion is triggered after semantic trigger chars (which are per-language) like `.`, `->` and `::` for C & C++. When you're just typing an identifier name, identifier completion is a much better choice since it works sooo much faster and we don't need to run the full clang compiler to figure out that by typing "foo", you are referring to the "foobar" identifier you created 3 lines ago.
