### ISSUE TITLE
Don't bind C-c Y

### ISSUE THREAD

**Issue by kriesoff** [abingham/emacs-ycmd#193]
"C-c <letter>" bindings are reserved for the user and should not be occupied by packages. Maybe it is possible to make the prefix key configurable.

**Comment by ptrv** [comment]
A lot of minor modes have their bindings on `C-c <some character>`. `C-c` is called `mode-specific-map`, so I really don't see a reason to not using it for minor-mode bindings. But it is a good idea to make the prefix customizable though.

**Comment by kriesoff** [comment]
I'm sorry, there was a typo on my part. I didn't mean all `C-c` bindings, only `C-c <letter>` (upper- and lowercase) are reserved, see [here](http://www.gnu.org/software/emacs/manual/html_node/elisp/Keymaps-and-Minor-Modes.html) and [here](http://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html). The rest of `mode-specific-map` is fine. I'm not sure about restricting minor modes to `C-c <punctuation>` as stated in the manual, that seems somewhat restrictive, and lots of minor modes don't conform to that. I don't know of (or don't use) any, though, that bind `C-c <letter>` by default. Anyways, making it configurable is fine, thanks.

**Comment by ptrv** [comment]
Thanks for the links to the Emacs coding conventions manual pages. You are completely right about `C-c <letter>` bindings. We should not use `C-c Y` as prefix and use something with `C-c <punctuation>` instead.

@abingham Any suggestions regarding a new prefix? What about `C-c ,`? Do you know if it is used for anything that could interfere with `ycmd-mode?

**Comment by abingham** [comment]
Since programming language modes can be quite mode-heavy, I think any prefix we choose has the potential to interfere with the bindings from other modes. For similar reasons, I've never really been comfortable with minor modes that defined too many bindings (like ycmd does, in fact), but at the same time providing keybindings is convenient for many users.

I guess a configurable prefix is fine. Packages like projectile and flycheck provide these, so I guess they play well with the rest of the emacs ecosystem. At the same time, if we make the prefix configurable, I don't see any problem keeping our current prefix by default. Projectile, for example, uses "C-c p" by default, so there's some precedent.

Another option is that we don't bind *any* keymap to the mode by default. We could then provide a function that sets up bindings, but the user would need to explicitly call this function (perhaps providing a prefix). We could even go so far as to call that function from `ycmd-setup`, i.e. if the user call `ycmd-setup` with a prefix then we'll arrange for the keybindings...otherwise we wouldn't set any.

I feel like I'm over-thinking this issues, though.

**Comment by ptrv** [comment]
@abingham I think having a prefix and making it configurable is the best. Let's keep `C-c Y` then.

**Comment by abingham** [comment]
Fixed in a489f4394e14a3825b2d04a77de740204f887031
