### ISSUE TITLE
Bind `url-show-status` temporarily to nil

### ISSUE THREAD

**Issue by phst** [abingham/emacs-ycmd#207]
The readme already suggests to set `url-show-status` to nil. However, the user can set this variable only globally with possible unwanted side effects like silencing important messages from other packages. I'd suggest to simply let-bind the variable to `nil` in `ycmd-request--url-retrieve`.

**Comment by abingham** [comment]
That's a good idea. We don't want to change it in `ycmd-request--url-retrieve`, though, because we hope that someday @tkf will fix some defects (i.e. apply some patches we've supplied) in `emacs-request` that let us switch back to it. What we can do, though, is let-bind it to `nil` in the places where we use `ycmd-request` and/or `ycmd-request-deferred`.

I suppose we could make this behavior configurable, e.g. with `ycmd-hide-request-status` or something which defaults to true. I can't think of a *great* reason someone would want the url status stuff, but I suppose it might be useful for debugging in some cases.

**Comment by abingham** [comment]
@phst Could you give the [hide-url-status](https://github.com/abingham/emacs-ycmd/tree/hide-url-status) branch a try? This adds the variable `ycmd-hide-url-status` which, when true, set `url-show-status` to `nil` for `emacs-ycmd` requests.

**Comment by ptrv** [comment]
This issue is now resolved with #209

**Comment by phst** [comment]
Seems to work, sorry for the huge delay and thanks for fixing.

**Comment by abingham** [comment]
Excellent, I'm glad it works for you!
