### ISSUE TITLE
ycmd abort trap 6

### ISSUE THREAD

**Issue by dongz9** [abingham/emacs-ycmd#225]
Hi,

I met this error every single time on Mac OS X.

Fatal Python error: PyThreadState_Get: no current thread

Process ycmd-server abort trap: 6

Any idea what's going on here?

**Comment by abingham** [comment]
This sounds more like a `ycmd` issue than one for the emacs client, so you should start there.

With that said, this kind of error commonly occurs when a compiled Python module (i.e. one written in C/C++) is loaded into a different version of Python that it was compiled for. You should try to figure out a) which version of Python the module was compiled for and b) what version you're running it in.

The variable `ycmd-server-command` determines how emacs runs ycmd, so that might be useful for you.

If you conclude that this is a ycmd issue, please close this. Otherwise explain, add some more information showing how it's related to `emacs-ycmd`.

**Comment by dongz9** [comment]
Thanks a lot for the reply! As you suspected, Emacs used a different version of Python. It's fixed now.
