### ISSUE TITLE
Figure out what's wrong with spacemacs

### ISSUE THREAD

**Issue by abingham** [abingham/emacs-ycmd#229]
There are a number of reports of weird behavior with spacemacs. See if you can get to the bottom of what's going on.

**Comment by abingham** [comment]
See #228. Here we uncovered issues related to some default spacemacs behavior.

**Comment by ptrv** [comment]
@abingham I am happy to see that the problem was found. I think that spacemacs does not do anything wrong and the `global_conf.py` file seems to be pretty useful since a `.clang_complete` is supported by other completion plugins for Emacs or other editors. The main issue here is the lack of information that is provided by `emacs-ycmd`. #242 addresses the issue and I think we can close this one, can't we?

**Comment by abingham** [comment]
I think you're right. I use spacemacs as my bases system now, and I haven't experience any other problems with it. If your upcoming PR provides better feedback and/or diagnostics for faulty ycmd configurations, then I think we're in good shape. Thanks!
