### ISSUE TITLE
Allow users to specify/bypass HTTP proxies for local traffic to ycmd

### ISSUE THREAD

**Issue by abingham** [abingham/emacs-ycmd#235]
We've seen cases where HTTP proxies are managing the traffic to ycmd, and in some cases this means it's sent through a firewall which block it. See for example #232.

In #232 @Alexander-Shukaev has some good suggestions on how we can approach this. The basic idea is to use a `let`to temporarily rebind `url-proxy-services` around our calls which generate HTTP traffic. Should be very straightforward.

**Comment by Alexander-Shukaev** [comment]
I just came up with one more suggestion.  For this `ycmd-url-proxy-services`, additionally to `nil` and actual values (acceptable by `url-proxy-services`), it could be possible to specify `'default`, which would mean that simply (the default) `url-proxy-services` is reused.  Otherwise, one would have to write something like `(setq ycmd-url-proxy-services url-proxy-services)`.
