### ISSUE TITLE
Add equivalent of ycm_min_num_of_chars_for_completion option

### ISSUE THREAD

**Issue by r4nt** [abingham/emacs-ycmd#276]
The vim config has this option, emacs users would like it, too.

**Comment by abingham** [comment]
Can this be managed through the use of variables like `company-minimum-prefix-length`?

**Comment by r4nt** [comment]
Nope, even when I set it to 0, I have to type 2 chars.

**Comment by ptrv** [comment]
If we add an defcustom for `ycm_min_num_of_chars_for_completion` we probably need to sync it somehow with the second argument of `company-grab-symbol-cons` in `company-ycmd--prefix`

**Comment by abingham** [comment]
Are those really related? I'll admit I'm a bit fuzzy on the protocol details, but it looks like that second argument is concerned with how far back company looks for the start RE. (What company does with the cons cell is where I haven't done any exploration).

I'm a bit puzzled that `company-minimum-prefix-length` doesn't "Just Work". Shouldn't it directly address @r4nt's concerns?

**Comment by ptrv** [comment]
@abingham Yes, you're right. The second argument of `company-grab-symbol-cons` is only for the amount of characters to look back.

If we set `company-minimum-prefix-length` to 0 there is still no completion because `ycmd` needs 2 characters to return completion candidates.

I guess if we add an option to set `ycm_min_num_of_chars_for_completion` we need also sync `company-minimum-prefix-length`.

**Comment by abingham** [comment]
@r4nt: I just merged in [@ptrv's patch](https://github.com/abingham/emacs-ycmd/pull/278) that should address your issue. Give it a shot and let us know how it goes.
