### ISSUE TITLE
Issue with upstream request not getting response on error

### ISSUE THREAD

**Issue by ptrv** [abingham/emacs-ycmd#297]
I noticed that with upstream request we get no response data when the server
returns an error. In my case it was a `UnknownExtraConf` exception that was not
caught with our exception handler. I looked at the differences of upstream
`request` and `ycmd-request` and found one line which causes this problem. In
`request.el` in the `request--callback` function in line
[648](https://github.com/tkf/emacs-request/blob/master/request.el#L648) the
response does not get parsed if the server errors. In `ycmd-request` there is
not such check and the response gets parse also in case of an error.

@abingham Could you try to repro this? I think we need to revert our change and
use again our `ycmd-request` version.

**Comment by abingham** [comment]
I think you're right about the code; they should remove that `unless` in the upstream request.el. We should go back to using our own version of request until they make that change.

I'll see about submitting a patch to the upstream request.el.

**Comment by abingham** [comment]
@ptrv Actually, I'm in a somewhat delicate position regarding my fork of emacs-request. My fork was the official MELPA version for a while so that we could make some pending patches available to the world. But now it seems tkf/emacs-request has diverged pretty significantly from my fork, and submitting patches from mine to his might be difficult/confusing. I'd delete my fork and just restart it, but I'm not entirely sure if anyone is depending on it anymore. I'm just being conservative.

Could you fork [the upstream request](https://github.com/tkf/emacs-request/), make the change you found, and submit a PR to them?

**Comment by ptrv** [comment]
@abingham I did a diff between you're fork and tks's version and the changes seem prettey small. Only defustom clean-up and adding a socket parameter for the curl part of emacs-request, which does not affect how we use  it.

I'll propose the change and try to explain.

I revert the change until they merge the "fix"

**Comment by ptrv** [comment]
I've submitted the PR: https://github.com/tkf/emacs-request/pull/44

**Comment by abingham** [comment]
Excellent, thanks!

**Comment by ptrv** [comment]
The PR in upstream `emacs-request` has been merged. I'll test it for a bit by using it though, before we get rid of `ycmd-request` again.

**Comment by ptrv** [comment]
Ok, seems that using upstream request is fine now. I revert the reverted commit.
