### ISSUE TITLE
ycmd-eldoc.el not included in the melpa recipe.

### ISSUE THREAD

**Issue by jiegec** [abingham/emacs-ycmd#302]
See https://github.com/melpa/melpa/blob/master/recipes/ycmd.

No auto-complete-ycmd either.

**Comment by ptrv** [comment]
That is by intention. The recipe contains only main `ycmd`.

We have separate packages for `company-ycmd` and `flycheck-ycmd`. 

For `ycmd-eldoc` I opened a PR: https://github.com/melpa/melpa/pull/3852

`auto-complete-ycmd` is hardly maintained and I don't even know if it works at all, since I don't use `auto-complete`. There were also no issues reported here so far.

**Comment by abingham** [comment]
Right, I would not expect `auto-complete-ycmd` to work at this point. We should probably consider getting rid of it so people aren't mislead!

**Comment by ptrv** [comment]
`ycmd-eldoc` is now included in the `ycmd` package. I first proposed a new recipe for `ycmd-eldoc` at MELPA but the maintainers suggested to include it in the main package since it has the same package dependencies as `ycmd`.

**Comment by ptrv** [comment]
`ycmd-eldoc` is now included in `ycmd` MELPA package

**Comment by jiegec** [comment]
Thanks.
