### ISSUE TITLE
flycheck-ycmd checks saved file, not current buffer contents

### ISSUE THREAD

**Issue by topiolli** [abingham/emacs-ycmd#350]
The flycheck integration seems to work on the file instead of the current buffer contents. I get correct reports after saving the buffer, but not while typing or when manually checking an unsaved buffer. If I fix the reported problems, flycheck still reports the errors in the file and only updates after save.

I'm a bit puzzled as code completion with company-ycmd works fine, which means that it sends the current buffer contents to the ycmd server. Why does it seem that flycheck-ycmd does not?

Emacs 24.3.1

Relevant ELPA packages:
ycmd-20160214.2344
flycheck-20160904.1622
flycheck-ycmd-20160808.754
company-20160211.520
company-ycmd-20160215.429

**Comment by ptrv** [comment]
`emacs-ycmd` sends the file contents to the server by sending a `FileReadyToParse` event. The response data of this event is then used by `flycheck-ycmd`. How often this event is sent to the server depends on the value of the variable `ycmd-parse-conditions`. It's a list and its default value is `'(save new-line mode-enabled)`. So, the buffer content is sent to the server when you save the file, you enter a new line or you enable `ycmd-mode` (when you open the file).

You can add also `idle-change` to the list. Then the file contents are sent to the server more or less when the buffer changes.

Since sending the file contents and waiting for the response can take longer in large projects, we disabled it by default.

Getting completion in `company-ycmd` is a bit different. We send a separate completion request event to the server and not the request to get diagnostic data for `flycheck`.

**Comment by topiolli** [comment]
Thanks for a quick reply. I need to play with the `idle-change` option and see if my project is too large. :) The current default works quite well when writing new code. However, correcting an existing problem often does not require a new line. I also have a tendency to introduce new problems while editing existing good code.

Would it be possible to detect a situation where the cursor moves from the current line after a modification? I'm thinking of something like saving the point in `pre-command-hook` and checking if the line changed in `post-command-hook`. If the line changed and there is a modification in between (detected by `after-change-functions`), parse.

**Comment by ptrv** [comment]
> Would it be possible to detect a situation where the cursor moves from the current line after a modification? I'm thinking of something like saving the point in pre-command-hook and checking if the line changed in post-command-hook. If the line changed and there is a modification in between (detected by after-change-functions), parse.

The `idle-change` setting is exactly for this. However there is also a small delay for parsing the file `ycmd-idle-change-delay`

**Comment by topiolli** [comment]
`idle-change` works for me, but it doesn't do exactly what I tried to suggest. In case of a large project - mine apparently isn't :) - delaying parsing until the point moves to another line would do about the same as the current default, but it would also work when modifying existing code. Parsing wouldn't be triggered unless the point moves to a new line. Currently, checking is triggered after a delay even if I stay on the same line. Moving to another line can be seen as an "I'm done with this line" indication, and I believe it could work as a logical trigger that causes less burden than `idle-change`.

**Comment by ptrv** [comment]
I really don't understand why we should not parse when a buffer changes but parse on a new line. I don't see a problem to save the buffer to update flycheck. We have the parse conditions to be able to configure the behaviour when to parse. For instant update of flycheck you only need to activate idle-change. IMHO I don't think a new line means always "I am finished with editing". Or maybe I just don't understand the problem here.

**Comment by topiolli** [comment]
Perhaps I don't have a point, or perhaps I'm unable to drive it home.

The whole point of on-the-fly checking is that it happens while editing. In that sense, the `idle-change` option is just what one would expect. But you said it causes a performance problem in large projects, which is why it was dropped from the default parse conditions.

> I really don't understand why we should not parse when a buffer changes but parse on a new line.

This is what the default setup currently does, so the logic seems to be accepted. The only difference to my suggestion is that `new-line` requires a new line to be actually entered. I thought it could be a reasonable compromise to track when the user moves away from the line she was editing. This would result in fewer parse requests but still retain the "on-the-fly" property of flycheck.

Anyhow, my project isn't too large for `idle-change`, so this isn't really a problem for me. I just wanted to suggest a feature I could see as an improvement for the current default setup.

**Comment by ptrv** [comment]
I now understand your suggestions. So basically if we have disabled `idle-change`, then trigger a parse when we go to a different line without entering an actual line.
This might be in some situations an improvement, but I am not sure the additional logic would justify the suggestions. I have to think about how to include the buffer modified check in order to be able to try to parse more often.

I close the issue since `idle-change` solves your problem.

Thanks for your suggestions.
