### ISSUE TITLE
Make client process failed

### ISSUE THREAD

**Issue by moyotar** [abingham/emacs-ycmd#385]
`ycmd` was normal at first'. But after using for a time. I got this and had to killed emacs from `cmd.exe`. Then, reopened emacs and it worked.

`open-network-stream: make client process failed: connection refused, :name, 127.0.0.1, :buffer, #<killed buffer>, :host, 127.0.0.1, :service, 5212, :nowait, nil`

**Comment by moyotar** [comment]
I find it's not easy to reproduce this error. I don't remember how I got it.

**Comment by ptrv** [comment]
This error shows that you are not using the latest `emacs-ycmd` because we removed a function in 05a029ecdc0566a3030c496d8ff200e3bcbd6140 that could cause an error like this.

Maybe you have a byte-compiled (`.elc` file) loaded instead the current version of `emacs-ycmd`?

Can you post the output of `M-x ycmd-versoin RET`?

I am closing this. Please reopen if you can provide a clear reporduction.

**Comment by moyotar** [comment]
Thanks! The command `ycmd-version` doesn't not exist. I updated `emacs-ycmd` by `el-get-update` and I will feed back if I meet it again.
