### ISSUE TITLE
support for /filter_and_sort_candidates server request

### ISSUE THREAD

**Issue by deb0ch** [abingham/emacs-ycmd#393]
Hi guys,

Is there any past or present reflexion about supporting the `/filter_and_sort_candidates` ycmd server command ?

Apparently it could be useful to get the fuzzy-matching and completion ranking for languages not explicitly supported by `ycmd`.

**Comment by abingham** [comment]
I haven't looked at that bit of API until now. How do you see it being used? I can see it being useful in principle, but I'm not sure how we'd best integrate it into the current system.

**Comment by deb0ch** [comment]
It is documented here: http://micbou.github.io/ycmd/#path--filter_and_sort_candidates. Not very easy to find, this is the ONLY documentation of ycmd's API that I have ever found and there isn't even a link to it in the main  docs of ycmd or YouCompleteMe.

> I can see it being useful in principle, but I'm not sure how we'd best integrate it into the current system.

This is why I'm asking, you are the one who knows the existing code :smile_cat:

Ofc I am willing to participate in the design / development process, I am just not sure how to go about it.

**Comment by abingham** [comment]
Interesting! I had the impression is was intended for use with ycmd's identifier-based completion, but they're really providing it for arbitrary sorting of identifiers from any source.

I think it would be fine (and relatively easy) to expose this function to emacs. It doesn't feel to me like part of the "core" ycmd functionality that we expose, so I'm tempted to put it into its own little package, e.g. `ycmd-services.el` or something like that. But maybe that's over-engineering; I'm happy to be convinced otherwise.

As for implementing it, I think it just boils down to calling:
```elisp
(ycmd--request "/filter_and_sort_candidates" content :parser 'json-read)
```
with `content` properly filled in by the client.

**Comment by ptrv** [comment]
That's really interesting. AFAIU the result of this request is supposed to be used as input data in an other completion engine/backend.

I think we could add a function like `ycmd-filter-and-sort-candidates` which takes a list of candidates and internally makes a request to `/filter_and_sort_candidates`. Since it is only one function I would not put it in a sepparate package also because to use the function you still need to include `ycmd.el` for the internals.

btw `:parser 'json-read` is not needed anymore for `ycmd--request`. We now always use `json-read`

**Comment by abingham** [comment]
> Since it is only one function I would not put it in a sepparate package
Fair enough. And the name `ycmd-filter-and-sort-candidates` is just right.

> btw :parser 'json-read is not needed anymore
Oops, right, I was looking at an old version of the code!

**Comment by vheon** [comment]
> Interesting! I had the impression is was intended for use with ycmd's identifier-based completion, but they're really providing it for arbitrary sorting of identifiers from any source.

Yes, we use it to support vim's omnifunction. So we get the candidates from one of vim's omnifunction for a language that we don't support natively, send the data to that api which sorts the caididates and returns them. I don't know if emacs has something similar to omnifunctions but I think it does.

> It is documented here: http://micbou.github.io/ycmd/#path--filter_and_sort_candidates. Not very easy to find, this is the ONLY documentation of ycmd's API that I have ever found and there isn't even a link to it in the main docs of ycmd or YouCompleteMe.

Yes, we currently don't have an official API Documentation (that one is actually a draft/experiment). Sorry about that :(

**Comment by deb0ch** [comment]
> Yes, we currently don't have an official API Documentation (that one is actually a draft/experiment). Sorry about that :(

Yeah, I had lots of trouble figuring things out (even reading the code base) until I randomly found this link, which basically saved my life.

Can't wait to see it released ! (Is it even planned ?)

**Comment by deb0ch** [comment]
Wow, I wasn't expecting such a fast and happy ending, thanks guys ! :thumbsup:

Now, I have to figure out how to integrate it to other completers :smirk_cat:

**Comment by abingham** [comment]
@ptrv did all of the hard work. I hope it works for you!

**Comment by deb0ch** [comment]
Will keep you updated when I get to it :smile_cat:
