### ISSUE TITLE
Completion type is [ID] and not the actual type

### ISSUE THREAD

**Issue by dmalyuta** [abingham/emacs-ycmd#432]
Consider the following code:
```
#include <iostream>
#include <eigen3/Eigen/Dense>

int main()
{
  Eigen::Vector3d myVector;
  myV
}
```
I trigger completion at the end of `myV` and I get back:
![image](https://user-images.githubusercontent.com/12475811/26997367-fbf7916c-4d2d-11e7-9d17-005382cb7fea.png)

What I think I should see is `myVector -> Eigen::Vector3d` in the completion list. Why is this is not what is displayed? Is it a general bug/problem with my setup?

**Comment by ptrv** [comment]
It's not a bug!

You're completion result comes from the identifier completer not from the filetype (semantic) completer. You trigger semantic completion after `.`, `->` or `::`.  This is by design. See here: https://github.com/Valloric/ycmd#how-ycmd-works

You can force semantic completion by calling `ycmd-toggle-force-semantic-completion` or having another function for semantic completion and bind it. See here https://github.com/abingham/emacs-ycmd/issues/183#issuecomment-97988875

Forcing always semantic completion can be slow for larger projects.
